### ISSUE TITLE
Run from Xcode

### ISSUE THREAD

**Issue by iadcialim** [M0Coding/Pokedex#8]
Is there a way to run the iOS app from Xcode?

**Comment by MohamedRejeb** [comment]
Yes, open the iOS .xcworkspace project on Xcode "ios/Pokedex.xcworkspace" and then you can run it.

**Note:** please make sure that you open Pokedex.xcworkspace not Pokedex.xcodeproj

**Comment by MohamedRejeb** [comment]
If you still having some issues with running the app on iOS feel free to reopen the issue.
